# Generated by Django 5.2.3 on 2025-07-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('otp', models.CharField(blank=True, max_length=10, null=True, verbose_name='one time password')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
