# Generated by Django 5.2.3 on 2025-07-04 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_otpdata_remove_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create'),
            preserve_default=False,
        ),
    ]
