# Generated by Django 5.2.3 on 2025-07-05 05:17

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_otpdata_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpdata',
            name='created_at',
        ),
        migrations.AddField(
            model_name='otpdata',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
