# Generated by Django 5.2.3 on 2025-07-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_otpdata_created_at_otpdata_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='otpdata',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='email'),
        ),
    ]
